# Generated by Django 6.0.4 on 2026-05-06 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
