# Generated by Django 6.0.4 on 2026-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('normalized_name', models.CharField(max_length=100)),
            ],
        ),
    ]
