# Generated by Django 6.0.4 on 2026-05-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredientalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
    ]
