# Generated by Django 6.0.4 on 2026-05-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_score_popularity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
    ]
