# Generated by Django 6.0.4 on 2026-05-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_shoppinglist_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
