# Generated by Django 6.0.4 on 2026-05-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_score_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
